# Dockerfile
FROM python:3.8

RUN apt-get update && apt-get install -y netcat-openbsd curl

WORKDIR /app

COPY requirements.txt .
COPY setup.py .

RUN pip install --no-cache-dir .

COPY . .

# Wait for Kafka and Neo4j to be ready
COPY wait-for-neo4j.sh .
RUN chmod +x wait-for-neo4j.sh

COPY wait-for-kafka.sh .
RUN chmod +x wait-for-kafka.sh

CMD ["./wait-for-neo4j.sh", "neo4j", "--", "./wait-for-kafka.sh", "kafka", "--", "faust", "-A", "app.stream.faust_app", "worker", "-l", "info"]