version: '3'

services:
  fast-data-dev:
    image: lensesio/box # alt: lensesio/fast-data-dev
    environment:
      ADV_HOST: fast-data-dev
      EULA: "https://licenses.lenses.io/download/lensesdl?id=68c647aa-e20f-11ee-bf14-42010af01003"
      SAMPLEDATA: 0
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://fast-data-dev:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 3030:3030  # Lenses UI
      - 29092:29092  # Kafka Broker
    networks:
      - fraud-detection

  # local -> neo4j@neo4j://localhost:7687
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["graph-data-science"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - fraud-detection

  fraud-detection-system:
    build: .
    depends_on:
      - fast-data-dev
      - neo4j
    networks:
      - fraud-detection


  # http://localhost:8000/docs
  # http://localhost:8000/api/events/customer-registration
  fraud-detection-api:
    build: .
    command: uvicorn app.main:fastapi_app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - fast-data-dev
      - neo4j
    networks:
      - fraud-detection

  fake-data-producer:
    build:
      context: .
      dockerfile: Dockerfile.fake-data-producer
    depends_on:
      - fast-data-dev
    restart: on-failure
    networks:
      - fraud-detection

networks:
  fraud-detection:
    name: fraud-detection-network
