version: '3'

services:
  kafka:
    image: lensesio/box # alt: lensesio/fast-data-dev
    environment:
      ADV_HOST: kafka
      EULA: "https://licenses.lenses.io/download/lensesdl?id=68c647aa-e20f-11ee-bf14-42010af01003"
      SAMPLEDATA: 0
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_COMPRESSION_TYPE: lz4
    ports:
      - 3030:3030  # Lenses UI
      - 29092:29092  # Kafka Broker
    networks:
      - zenith

  # local -> neo4j@neo4j://localhost:7687
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["graph-data-science"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - zenith

  # redis:
  #   image: redis:6.2
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  # mongodb:
  #   image: mongo:4.4
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

  zenith-api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - neo4j
    networks:
      - zenith

  zenith-worker:
    build:
      context: .
      dockerfile: Dockerfile.faust-worker
    depends_on:
      - kafka
      - neo4j
    networks:
      - zenith

volumes:
  redis_data:
  mongodb_data:

networks:
  zenith:
    name: zenith
